name: Publish container disk images

on:
  push:
    branches:
    - main
    paths:
    - 'build-container-disk-image.sh'
    - 'Makefile'
    - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login in dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and publish container disk images
      run: |
        make all
